
package com.ming.ketuo.webserviceforfind;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceForFindSoap", targetNamespace = "http://www.keytop.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceForFindSoap {


    /**
     * APP授权车辆作为临时停车进场
     * 
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReserveSpace", action = "http://www.keytop.com.cn/ReserveSpace")
    @WebResult(name = "ReserveSpaceResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "ReserveSpace", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.ReserveSpace")
    @ResponseWrapper(localName = "ReserveSpaceResponse", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.ReserveSpaceResponse")
    public String reserveSpace(
        @WebParam(name = "data", targetNamespace = "http://www.keytop.com.cn/")
        String data);

}
