
package com.ming.ketuo.webserviceforfind;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceForFind", targetNamespace = "http://www.keytop.com.cn/", wsdlLocation = "http://172.16.24.210:8099/webserviceforfind.asmx?wsdl")
public class WebServiceForFind
    extends Service
{

    private final static URL WEBSERVICEFORFIND_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEFORFIND_EXCEPTION;
    private final static QName WEBSERVICEFORFIND_QNAME = new QName("http://www.keytop.com.cn/", "WebServiceForFind");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.24.210:8099/webserviceforfind.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEFORFIND_WSDL_LOCATION = url;
        WEBSERVICEFORFIND_EXCEPTION = e;
    }

    public WebServiceForFind() {
        super(__getWsdlLocation(), WEBSERVICEFORFIND_QNAME);
    }

    public WebServiceForFind(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEFORFIND_QNAME, features);
    }

    public WebServiceForFind(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEFORFIND_QNAME);
    }

    public WebServiceForFind(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEFORFIND_QNAME, features);
    }

    public WebServiceForFind(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceForFind(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceForFindSoap
     */
    @WebEndpoint(name = "WebServiceForFindSoap")
    public WebServiceForFindSoap getWebServiceForFindSoap() {
        return super.getPort(new QName("http://www.keytop.com.cn/", "WebServiceForFindSoap"), WebServiceForFindSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceForFindSoap
     */
    @WebEndpoint(name = "WebServiceForFindSoap")
    public WebServiceForFindSoap getWebServiceForFindSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.keytop.com.cn/", "WebServiceForFindSoap"), WebServiceForFindSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEFORFIND_EXCEPTION!= null) {
            throw WEBSERVICEFORFIND_EXCEPTION;
        }
        return WEBSERVICEFORFIND_WSDL_LOCATION;
    }

}
