
package com.ming.weather.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherServiceSoap", targetNamespace = "http://www.36wu.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherServiceSoap {


    /**
     * <h3>ʵʱ����</h3>
     * 
     * @param authkey
     * @param district
     * @return
     *     returns com._36wu.ResultOfTodayWeather
     */
    @WebMethod(operationName = "GetWeather", action = "http://www.36wu.com/GetWeather")
    @WebResult(name = "GetWeatherResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetWeather", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeather")
    @ResponseWrapper(localName = "GetWeatherResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeatherResponse")
    public ResultOfTodayWeather getWeather(
        @WebParam(name = "district", targetNamespace = "http://www.36wu.com/")
        String district,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        String authkey);

    /**
     * <h3>IP���ܵ���ʵʱ����</h3>
     * 
     * @param authkey
     * @param ip
     * @return
     *     returns com._36wu.ResultOfTodayWeather
     */
    @WebMethod(operationName = "GetWeatherByIp", action = "http://www.36wu.com/GetWeatherByIp")
    @WebResult(name = "GetWeatherByIpResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetWeatherByIp", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeatherByIp")
    @ResponseWrapper(localName = "GetWeatherByIpResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeatherByIpResponse")
    public ResultOfTodayWeather getWeatherByIp(
        @WebParam(name = "ip", targetNamespace = "http://www.36wu.com/")
        String ip,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        String authkey);

    /**
     * <h3>��γ�����ܵ���ʵʱ����</h3>
     * 
     * @param authkey
     * @param lng
     * @param lat
     * @return
     *     returns com._36wu.ResultOfTodayWeather
     */
    @WebMethod(operationName = "GetWeatherByLocation", action = "http://www.36wu.com/GetWeatherByLocation")
    @WebResult(name = "GetWeatherByLocationResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetWeatherByLocation", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeatherByLocation")
    @ResponseWrapper(localName = "GetWeatherByLocationResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeatherByLocationResponse")
    public ResultOfTodayWeather getWeatherByLocation(
        @WebParam(name = "lat", targetNamespace = "http://www.36wu.com/")
        float lat,
        @WebParam(name = "lng", targetNamespace = "http://www.36wu.com/")
        float lng,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        String authkey);

    /**
     * <h3>δ��һ������</h3>
     * 
     * @param authkey
     * @param district
     * @return
     *     returns com._36wu.ResultOfMoreWeather
     */
    @WebMethod(operationName = "GetMoreWeather", action = "http://www.36wu.com/GetMoreWeather")
    @WebResult(name = "GetMoreWeatherResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetMoreWeather", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetMoreWeather")
    @ResponseWrapper(localName = "GetMoreWeatherResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetMoreWeatherResponse")
    public ResultOfMoreWeather getMoreWeather(
        @WebParam(name = "district", targetNamespace = "http://www.36wu.com/")
        String district,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        String authkey);

    /**
     * <h3>IP���ܵ���δ��һ������</h3>
     * 
     * @param authkey
     * @param ip
     * @return
     *     returns com._36wu.ResultOfMoreWeather
     */
    @WebMethod(operationName = "GetMoreWeatherByIp", action = "http://www.36wu.com/GetMoreWeatherByIp")
    @WebResult(name = "GetMoreWeatherByIpResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetMoreWeatherByIp", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetMoreWeatherByIp")
    @ResponseWrapper(localName = "GetMoreWeatherByIpResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetMoreWeatherByIpResponse")
    public ResultOfMoreWeather getMoreWeatherByIp(
        @WebParam(name = "ip", targetNamespace = "http://www.36wu.com/")
        String ip,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        String authkey);

    /**
     * <h3>��γ�����ܵ���δ��һ������</h3>
     * 
     * @param authkey
     * @param lng
     * @param lat
     * @return
     *     returns com._36wu.ResultOfMoreWeather
     */
    @WebMethod(operationName = "GetMoreWeatherByLocation", action = "http://www.36wu.com/GetMoreWeatherByLocation")
    @WebResult(name = "GetMoreWeatherByLocationResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetMoreWeatherByLocation", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetMoreWeatherByLocation")
    @ResponseWrapper(localName = "GetMoreWeatherByLocationResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetMoreWeatherByLocationResponse")
    public ResultOfMoreWeather getMoreWeatherByLocation(
        @WebParam(name = "lat", targetNamespace = "http://www.36wu.com/")
        float lat,
        @WebParam(name = "lng", targetNamespace = "http://www.36wu.com/")
        float lng,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        String authkey);

    /**
     * <h3>�������ָ��</h3>
     * 
     * @param authkey
     * @param district
     * @return
     *     returns com._36wu.ResultOfWeatherIndex
     */
    @WebMethod(operationName = "GetWeatherIndex", action = "http://www.36wu.com/GetWeatherIndex")
    @WebResult(name = "GetWeatherIndexResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetWeatherIndex", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeatherIndex")
    @ResponseWrapper(localName = "GetWeatherIndexResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeatherIndexResponse")
    public ResultOfWeatherIndex getWeatherIndex(
        @WebParam(name = "district", targetNamespace = "http://www.36wu.com/")
        String district,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        String authkey);

    /**
     * <h3>��ʷ�����ѯ</h3>
     * 
     * @param authkey
     * @param start
     * @param district
     * @param end
     * @return
     *     returns com._36wu.ResultOfListOfHistoricalWeather
     */
    @WebMethod(operationName = "GetHistoricalWeather", action = "http://www.36wu.com/GetHistoricalWeather")
    @WebResult(name = "GetHistoricalWeatherResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetHistoricalWeather", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetHistoricalWeather")
    @ResponseWrapper(localName = "GetHistoricalWeatherResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetHistoricalWeatherResponse")
    public ResultOfListOfHistoricalWeather getHistoricalWeather(
        @WebParam(name = "district", targetNamespace = "http://www.36wu.com/")
        String district,
        @WebParam(name = "start", targetNamespace = "http://www.36wu.com/")
        String start,
        @WebParam(name = "end", targetNamespace = "http://www.36wu.com/")
        String end,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        String authkey);

    /**
     * <h3>֧�ֳ����б�</h3>
     * 
     * @param authkey
     * @return
     *     returns com._36wu.ResultOfListOfArea
     */
    @WebMethod(operationName = "GetAreaList", action = "http://www.36wu.com/GetAreaList")
    @WebResult(name = "GetAreaListResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetAreaList", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetAreaList")
    @ResponseWrapper(localName = "GetAreaListResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetAreaListResponse")
    public ResultOfListOfArea getAreaList(
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        String authkey);

}
