
package com.ming.ip.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IpService", targetNamespace = "http://www.36wu.com/", wsdlLocation = "http://web.36wu.com/IpService.asmx?wsdl")
public class IpService
    extends Service
{

    private final static URL IPSERVICE_WSDL_LOCATION;
    private final static WebServiceException IPSERVICE_EXCEPTION;
    private final static QName IPSERVICE_QNAME = new QName("http://www.36wu.com/", "IpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://web.36wu.com/IpService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IPSERVICE_WSDL_LOCATION = url;
        IPSERVICE_EXCEPTION = e;
    }

    public IpService() {
        super(__getWsdlLocation(), IPSERVICE_QNAME);
    }

    public IpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IPSERVICE_QNAME, features);
    }

    public IpService(URL wsdlLocation) {
        super(wsdlLocation, IPSERVICE_QNAME);
    }

    public IpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IPSERVICE_QNAME, features);
    }

    public IpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IpServiceSoap
     */
    @WebEndpoint(name = "IpServiceSoap")
    public IpServiceSoap getIpServiceSoap() {
        return super.getPort(new QName("http://www.36wu.com/", "IpServiceSoap"), IpServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IpServiceSoap
     */
    @WebEndpoint(name = "IpServiceSoap")
    public IpServiceSoap getIpServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.36wu.com/", "IpServiceSoap"), IpServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IPSERVICE_EXCEPTION!= null) {
            throw IPSERVICE_EXCEPTION;
        }
        return IPSERVICE_WSDL_LOCATION;
    }

}
