
package com.ming.ip.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IpServiceSoap", targetNamespace = "http://www.36wu.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IpServiceSoap {


    /**
     * <h3>IP��ַ��ѯ</h3>
     * 
     * @param authkey
     * @param ip
     * @return
     *     returns com._36wu.ResultOfIpInfo
     */
    @WebMethod(operationName = "GetIpInfo", action = "http://www.36wu.com/GetIpInfo")
    @WebResult(name = "GetIpInfoResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetIpInfo", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetIpInfo")
    @ResponseWrapper(localName = "GetIpInfoResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetIpInfoResponse")
    public ResultOfIpInfo getIpInfo(
        @WebParam(name = "ip", targetNamespace = "http://www.36wu.com/")
        String ip,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        String authkey);

    /**
     * <h3>IP��λ��ѯ</h3>
     * 
     * @param authkey
     * @param ip
     * @return
     *     returns com._36wu.ResultOfLocationInfo
     */
    @WebMethod(operationName = "GetLocationInfo", action = "http://www.36wu.com/GetLocationInfo")
    @WebResult(name = "GetLocationInfoResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetLocationInfo", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetLocationInfo")
    @ResponseWrapper(localName = "GetLocationInfoResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetLocationInfoResponse")
    public ResultOfLocationInfo getLocationInfo(
        @WebParam(name = "ip", targetNamespace = "http://www.36wu.com/")
        String ip,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        String authkey);

}
