
package com.ming.ketuo.webserviceforpay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceForPaySoap", targetNamespace = "http://www.keytop.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceForPaySoap {


    /**
     * 停车费订单查询接口
     * 
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetParkingPaymentInfo", action = "http://www.keytop.com.cn/GetParkingPaymentInfo")
    @WebResult(name = "GetParkingPaymentInfoResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetParkingPaymentInfo", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.GetParkingPaymentInfo")
    @ResponseWrapper(localName = "GetParkingPaymentInfoResponse", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.GetParkingPaymentInfoResponse")
    public String getParkingPaymentInfo(
        @WebParam(name = "data", targetNamespace = "http://www.keytop.com.cn/")
        String data);

    /**
     * 停车费订单支付接口
     * 
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PayParkingFee", action = "http://www.keytop.com.cn/PayParkingFee")
    @WebResult(name = "PayParkingFeeResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "PayParkingFee", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.PayParkingFee")
    @ResponseWrapper(localName = "PayParkingFeeResponse", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.PayParkingFeeResponse")
    public String payParkingFee(
        @WebParam(name = "data", targetNamespace = "http://www.keytop.com.cn/")
        String data);

    /**
     * 查询缴费记录
     * 
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryCarPrePaidDetail", action = "http://www.keytop.com.cn/QueryCarPrePaidDetail")
    @WebResult(name = "QueryCarPrePaidDetailResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "QueryCarPrePaidDetail", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.QueryCarPrePaidDetail")
    @ResponseWrapper(localName = "QueryCarPrePaidDetailResponse", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.QueryCarPrePaidDetailResponse")
    public String queryCarPrePaidDetail(
        @WebParam(name = "data", targetNamespace = "http://www.keytop.com.cn/")
        String data);

}
