
package com.ming.ketuo.webserviceforsys;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceForSysSoap", targetNamespace = "http://www.keytop.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceForSysSoap {


    /**
     * 变更月租车车牌
     * 
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ModifyCardBindCar", action = "http://www.keytop.com.cn/ModifyCardBindCar")
    @WebResult(name = "ModifyCardBindCarResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "ModifyCardBindCar", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.ModifyCardBindCar")
    @ResponseWrapper(localName = "ModifyCardBindCarResponse", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.ModifyCardBindCarResponse")
    public String modifyCardBindCar(
        @WebParam(name = "data", targetNamespace = "http://www.keytop.com.cn/")
        String data);

    /**
     * 下发客户信息
     * 
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DistributeCustomInfo", action = "http://www.keytop.com.cn/DistributeCustomInfo")
    @WebResult(name = "DistributeCustomInfoResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "DistributeCustomInfo", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.DistributeCustomInfo")
    @ResponseWrapper(localName = "DistributeCustomInfoResponse", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.DistributeCustomInfoResponse")
    public String distributeCustomInfo(
        @WebParam(name = "data", targetNamespace = "http://www.keytop.com.cn/")
        String data);

    /**
     * 下发操作员信息
     * 
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DistributeCasherInfo", action = "http://www.keytop.com.cn/DistributeCasherInfo")
    @WebResult(name = "DistributeCasherInfoResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "DistributeCasherInfo", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.DistributeCasherInfo")
    @ResponseWrapper(localName = "DistributeCasherInfoResponse", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.DistributeCasherInfoResponse")
    public String distributeCasherInfo(
        @WebParam(name = "data", targetNamespace = "http://www.keytop.com.cn/")
        String data);

    /**
     * 下发无卡延期操作
     * 
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DistributeCarCardChargeInfo", action = "http://www.keytop.com.cn/DistributeCarCardChargeInfo")
    @WebResult(name = "DistributeCarCardChargeInfoResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "DistributeCarCardChargeInfo", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.DistributeCarCardChargeInfo")
    @ResponseWrapper(localName = "DistributeCarCardChargeInfoResponse", targetNamespace = "http://www.keytop.com.cn/", className = "cn.com.keytop.DistributeCarCardChargeInfoResponse")
    public String distributeCarCardChargeInfo(
        @WebParam(name = "data", targetNamespace = "http://www.keytop.com.cn/")
        String data);

}
