
package com.ming.ketuo.webserviceforsys;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceForSys", targetNamespace = "http://www.keytop.com.cn/", wsdlLocation = "http://172.16.24.210:8099/webserviceforsys.asmx?wsdl")
public class WebServiceForSys
    extends Service
{

    private final static URL WEBSERVICEFORSYS_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEFORSYS_EXCEPTION;
    private final static QName WEBSERVICEFORSYS_QNAME = new QName("http://www.keytop.com.cn/", "WebServiceForSys");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.24.210:8099/webserviceforsys.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEFORSYS_WSDL_LOCATION = url;
        WEBSERVICEFORSYS_EXCEPTION = e;
    }

    public WebServiceForSys() {
        super(__getWsdlLocation(), WEBSERVICEFORSYS_QNAME);
    }

    public WebServiceForSys(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEFORSYS_QNAME, features);
    }

    public WebServiceForSys(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEFORSYS_QNAME);
    }

    public WebServiceForSys(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEFORSYS_QNAME, features);
    }

    public WebServiceForSys(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceForSys(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceForSysSoap
     */
    @WebEndpoint(name = "WebServiceForSysSoap")
    public WebServiceForSysSoap getWebServiceForSysSoap() {
        return super.getPort(new QName("http://www.keytop.com.cn/", "WebServiceForSysSoap"), WebServiceForSysSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceForSysSoap
     */
    @WebEndpoint(name = "WebServiceForSysSoap")
    public WebServiceForSysSoap getWebServiceForSysSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.keytop.com.cn/", "WebServiceForSysSoap"), WebServiceForSysSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEFORSYS_EXCEPTION!= null) {
            throw WEBSERVICEFORSYS_EXCEPTION;
        }
        return WEBSERVICEFORSYS_WSDL_LOCATION;
    }

}
